// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Wed Feb  4 01:12:50 2026

four2one four2one_inst
(
	.SEL(SEL_sig) ,	// input [1:0] SEL_sig
	.D0(D0_sig) ,	// input [3:0] D0_sig
	.D1(D1_sig) ,	// input [3:0] D1_sig
	.D2(D2_sig) ,	// input [3:0] D2_sig
	.D3(D3_sig) ,	// input [3:0] D3_sig
	.Y(Y_sig) 	// output [3:0] Y_sig
);

