// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Wed Feb  4 00:23:18 2026

keypad_input keypad_input_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) ,	// input  reset_sig
	.row(row_sig) ,	// input [3:0] row_sig
	.col(col_sig) ,	// output [3:0] col_sig
	.out(out_sig) ,	// output [((DIGITS*4)-1):0] out_sig
	.value(value_sig) ,	// output [3:0] value_sig
	.trig(trig_sig) 	// output  trig_sig
);

defparam keypad_input_inst.DIGITS = 4;
