// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Wed Feb  4 01:20:06 2026

Multi7segdisplay Multi7segdisplay_inst
(
	.HEX0(HEX0_sig) ,	// input [3:0] HEX0_sig
	.HEX1(HEX1_sig) ,	// input [3:0] HEX1_sig
	.HEX2(HEX2_sig) ,	// input [3:0] HEX2_sig
	.HEX3(HEX3_sig) ,	// input [3:0] HEX3_sig
	.CLK(CLK_sig) ,	// input  CLK_sig
	.Reset(Reset_sig) ,	// input  Reset_sig
	.Load(Load_sig) ,	// input  Load_sig
	.SEG(SEG_sig) ,	// output [0:6] SEG_sig
	.CAT(CAT_sig) 	// output [3:0] CAT_sig
);

