// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Sun Apr 26 19:04:22 2026

OverflowUnderflow OverflowUnderflow_inst
(
	.EA(EA_sig) ,	// input [4:0] EA_sig
	.EB(EB_sig) ,	// input [4:0] EB_sig
	.finalmantissa(finalmantissa_sig) ,	// input [9:0] finalmantissa_sig
	.finalexponent(finalexponent_sig) ,	// input [5:0] finalexponent_sig
	.exponentsubtractorcout(exponentsubtractorcout_sig) ,	// input  exponentsubtractorcout_sig
	.Overflow(Overflow_sig) ,	// output  Overflow_sig
	.Underflow(Underflow_sig) 	// output  Underflow_sig
);

