// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Tue Feb  3 23:18:33 2026

keypad_base keypad_base_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.row(row_sig) ,	// input [3:0] row_sig
	.col(col_sig) ,	// output [3:0] col_sig
	.value(value_sig) ,	// output [3:0] value_sig
	.valid(valid_sig) ,	// output  valid_sig
	.slow_clock(slow_clock_sig) ,	// output  slow_clock_sig
	.sense(sense_sig) ,	// output  sense_sig
	.valid_digit(valid_digit_sig) ,	// output  valid_digit_sig
	.inv_row(inv_row_sig) 	// output [3:0] inv_row_sig
);

