// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Mon Apr 20 00:40:19 2026

ControlledExponent_INC_DEC ControlledExponent_INC_DEC_inst
(
	.A(A_sig) ,	// input [4:0] A_sig
	.select(select_sig) ,	// input  select_sig
	.cin(cin_sig) ,	// input  cin_sig
	.exponent(exponent_sig) 	// output [4:0] exponent_sig
);

