// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Tue Feb  3 23:50:32 2026

shift_reg shift_reg_inst
(
	.trig(trig_sig) ,	// input  trig_sig
	.reset(reset_sig) ,	// input  reset_sig
	.dir(dir_sig) ,	// input  dir_sig
	.in(in_sig) ,	// input [(WIDTH-1):0] in_sig
	.out(out_sig) 	// output [((COUNT*WIDTH)-1):0] out_sig
);

defparam shift_reg_inst.COUNT = 4;
defparam shift_reg_inst.WIDTH = 4;
