// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 24.1 (Build Build 1077 03/04/2025)
// Created on Mon Apr 20 21:48:51 2026

CSA CSA_inst
(
	.A(A_sig) ,	// input [10:0] A_sig
	.B(B_sig) ,	// input [10:0] B_sig
	.Cin(Cin_sig) ,	// input  Cin_sig
	.Sum(Sum_sig) ,	// output [10:0] Sum_sig
	.Cout(Cout_sig) 	// output  Cout_sig
);

